### ISSUE TITLE
Call to a member function getId() on a non-object

### ISSUE THREAD

**Issue by coresh** [colinmollenhour/Cm_Diehard#22]
# Sometimes fired an issue:

##### Issue was affected to the file: 
```javascript
app/design/frontend/base/default/template/core/formkey.phtml
```
##### PS: file:
```javascript
app/design/frontend/base/default/template/core/formkey.phtml
```
##### Exists, with content:
```php
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
```
##### With permission:
```bash
$ ls -la app/design/frontend/base/default/template/core/formkey.phtml
-rwxrwxr-x. 1 www-data www-data 1083 Feb 14 18:09 app/design/frontend/base/default/template/core/formkey.phtml
```
##### Log output:
```javascript
$ tail -1000 var/report/1438582095995
a:5:{i:0;s:56:"Call to a member function getId() on a non-object (NULL)";i:1;s:2695:"#0 .modman/Cm_Diehard/Mage/Core/Block/Template.php(250): include()
#1 .modman/Cm_Diehard/Mage/Core/Block/Template.php(281): Mage_Core_Block_Template->fetchView()
#2 .modman/Cm_Diehard/Mage/Core/Block/Template.php(295): Mage_Core_Block_Template->renderView()
#3 .modman/Cm_Diehard/Mage/Core/Block/Abstract.php(936): Mage_Core_Block_Template->_toHtml()
#4 app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#5 .modman/Cm_Diehard/Mage/Core/Block/Abstract.php(936): Mage_Core_Block_Text_List->_toHtml()
#6 .modman/Cm_Diehard/Mage/Core/Block/Abstract.php(642): Mage_Core_Block_Abstract->toHtml()
#7 .modman/Cm_Diehard/Mage/Core/Block/Abstract.php(586): Mage_Core_Block_Abstract->_getChildHtml()
#8 app/design/frontend/rwd/cdf/template/page/1column.phtml(55): Mage_Core_Block_Abstract->getChildHtml()
#9 .modman/Cm_Diehard/Mage/Core/Block/Template.php(250): include()
#10 .modman/Cm_Diehard/Mage/Core/Block/Template.php(281): Mage_Core_Block_Template->fetchView()
#11 .modman/Cm_Diehard/Mage/Core/Block/Template.php(295): Mage_Core_Block_Template->renderView()
#12 .modman/Cm_Diehard/Mage/Core/Block/Abstract.php(936): Mage_Core_Block_Template->_toHtml()
#13 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#14 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#15 app/code/local/Act/Locale/controllers/CartController.php(261): Mage_Core_Controller_Varien_Action->renderLayout()
#16 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Act_Locale_CartController->indexAction()
#17 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch()
#18 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#19 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 app/Mage.php(684): Mage_Core_Model_App->run()
#21 pub/index.php(268): Mage::run()
#22 {main}";s:3:"url";s:21:"/en_us/checkout/cart/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"en_us";}%
```

**Comment by colinmollenhour** [comment]
That is odd since the stack trace doesn't really seem to show where the error lies. It usually has arguments listed between the (), were these omitted?

Do you have the cart page enabled for caching? Since this page will vary for every user and should contain session messages and such I would not recommend caching it if you are.

**Comment by coresh** [comment]
General issue was occurring concerning to child block error (another .phtml file) and in this case not affected to Cm_Diehard extention

Please close this issue
